### ISSUE TITLE
Replication plan always changes after 'deletion' option is edited once

### ISSUE THREAD

**Issue by yogeek** [goharbor/terraform-provider-harbor#181]
When creating a replication with this code :
```
resource "harbor_replication" "proxycache-cn-north-1" {
  name        = "proxycache-cn-north-1"
  action      = "push"
  override    = false
  registry_id = harbor_registry.cn-north-1.registry_id
  schedule    = "0 */10 * * * *"
  filters {
    name = "cdsf/**"
  }
  filters {
    resource = "image"
  }
}
```

the creation is ok.

But then, if we update the replication in Harbor UI to set to `even_based` with deletion enabled we have this result at the next terraform launch (which is normal):

```
# harbor_replication.proxycache-cn-north-1 will be updated in-place

  ~ resource "harbor_replication" "proxycache-cn-north-1" {
      ~ deletion              = true -> false
        id                    = "/replication/policies/10"
        name                  = "proxycache-cn-north-1"
      ~ schedule              = "manual" -> "0 */10 * * * *"
        # (5 unchanged attributes hidden)
        # (2 unchanged blocks hidden)
    }
```

but after applying :
- the schedule part is modified as planned
- the deletion is not modified (because the schedule mode is `event_based` which does not have the `delete` option)

And from there, the deletion change will always appears in all the next terraform plans without changing any code : 
` ~ deletion              = true -> false`

Harbor Version v2.4.0-d4affc2e
Provider version : 3.4.4

Additionnal point : when we look at the documentation, the `even_based` is missing (only  manual and schedule are).

**Comment by flbla** [comment]
hi,
with latest terraform provider, I don't have the issue
