### ISSUE TITLE
Inconsistency on replication rules format between harbor and provider

### ISSUE THREAD

**Issue by yogeek** [goharbor/terraform-provider-harbor#182]
Since this modification in Harbor : https://github.com/goharbor/harbor/pull/14345, harbor adds `{` and `}` on any rule containing a `,`.
This behavior does not seem to be applied in the provider which implies that if we configure a rule without '{' in the terraform code, the rule is not valid for harbor and ignored.

It can lead to some important issues because it has for consequences some deletion on images we wanted to retain.

Harbor Version v2.4.0-d4affc2e
Provider version : 3.4.4

**Comment by naitmare01** [comment]
Maybe something like adding a string-manipulation to add `{` and `}` on the below rows would suffice?

https://github.com/goharbor/terraform-provider-harbor/blob/main/client/replication.go#L55
```hcl
if name != "" {
	filter.Type = "name"
	filter.Value = name
}
if tag != "" {
	filter.Type = "tag"
	filter.Value = strings.ReplaceAll(tag, " ", "")
	filter.Decoration = decoration
}
