### ISSUE TITLE
Tag_matching list bug 

### ISSUE THREAD

**Issue by pkalemba** [goharbor/terraform-provider-harbor#196]
**Describe the bug**
When you are trying add a comma separated list to `tag_matching` field , rules are ommited.

**To Reproduce**
use resource like this: 
```
resource "harbor_retention_policy" "XXXX" {
  scope    = harbor_project.XXX.id
  schedule = "Hourly"
  rule {
    repo_matching          = "**"
    n_days_since_last_push = 14
    tag_matching           = "foo*,bar*"
    untagged_artifacts     = false
  }
}
```

This list is added a a literal string , and its seen on harbor db, when I add it via UI 
`pattern`  field is a json list: `"pattern": "{foo*,bar*}",`

**Comment by HammerNL89** [comment]
I'm facing the same issue, can't add multiple tags.

**Comment by pkalemba** [comment]
@HammerNL89 workaround: 
`tag_matching           = "{foo*,bar*}"`

But this is ugly hack :/

**Comment by naitmare01** [comment]
We got hit with the same issue and managed to track it to https://github.com/goharbor/harbor/issues/14961

**Comment by SimonAlling** [comment]
> @HammerNL89 workaround: `tag_matching = "{foo*,bar*}"`
> 
> But this is ugly hack :/

Well … you could argue that it's Harbor that does the ugly hack, by [implicitly wrapping the input in curly brackets if the input contains a `,` and doesn't contain a `{` and a `}` (at any position)](https://github.com/goharbor/harbor/blob/5a4f6c6167cfaca8f9ea6a7512a2d1b94fa2ae85/src/portal/src/app/base/project/tag-feature-integration/immutable-tag/add-rule/add-immutable-rule.component.ts#L123:L131).

**Comment by SimonAlling** [comment]
> This list is added a a literal string , and its seen on harbor db, when I add it via UI `pattern` field is a json list: `"pattern": "{foo*,bar*}",`

Not JSON – it is a [`doublestar` pattern](https://github.com/bmatcuk/doublestar#patterns).

**Comment by SimonAlling** [comment]
We could either try to replicate Harbor's behavior (probably error-prone and brittle) or update the documentation appropriately.
