### ISSUE TITLE
harbor_project_membership_user always drifts between apply runs due to changed username

### ISSUE THREAD

**Issue by deepbrook** [goharbor/terraform-provider-harbor#221]
**Describe the bug**

**To Reproduce**
```hcl
resource "harbor_project" "purpose" {
  name                   = "my-project"
  public                 = "true"
  vulnerability_scanning = "true"
  deployment_security    = "critical"
  enable_content_trust   = "false"
  force_destroy          = false
}


resource "harbor_project_member_user" "admins" {
  for_each      = toset(["vendrell"])
  project_id    = harbor_project.purpose.id
  user_name   = each.value
  role          = "projectadmin"
}
```

When running `terraform plan` I consistently get a replace action on the membership resources, due to the username being something different than I state in the resource block:

```shell
  # module.harbor.harbor_project_member_user.admins["vendrell"] must be replaced
-/+ resource "harbor_project_member_user" "admins" {
      ~ id         = "/projects/1304/members/957" -> (known after apply)
      + member_id  = (known after apply)
      ~ user_name  = "Vendrell" -> "vendrell" # forces replacement
        # (2 unchanged attributes hidden)
    }
```
If I run apply and plan again, *this* is the output:
```shell
  # module.harbor.harbor_project_member_user.admins["vendrell"] must be replaced
-/+ resource "harbor_project_member_user" "admins" {
      ~ id         = "/projects/1304/members/957" -> (known after apply)
      + member_id  = (known after apply)
      ~ user_name  = "vendrell" -> "Vendrell" # forces replacement
        # (2 unchanged attributes hidden)
    }
```

The interesting bit is that it seemingly does not matter whether or not I try to normalize the value of `username` using `lower()`, `upper()` or `title()` - the username is *always* different and forces the resource to be replaced.

**Expected behavior**
There should be no changes required, as the user and membership did not change.

**Additional context**
We primarily use LDAP groups to manage group memberships - I opted to not use a group in this instance, because I need to assign the same collection of people to several projects as admins, but cannot do so as there is no group resource to share between configurations.

Provider version is `3.7.1`, terraform version is `v1.0.9`.

**Comment by flbla** [comment]
Hi,
I don't have the issue with latest provider
I close the issue feel free to re-open it if needed
