### ISSUE TITLE
Does not handle missing resources (e.g. registry)

### ISSUE THREAD

**Issue by taliesins** [goharbor/terraform-provider-harbor#237]
**Describe the bug**
If resources are created by the provider and then changes occur outside of provider it is not handled gracefully. When someone manually renames or deletes the registry it will cause the provider to crash as in its state file it expects a registry to exist and it is unable to retrieve it.

**To Reproduce**
1. Create registry via Terraform code
2. Apply Terraform code
3. Manually delete registry
4. Remove registry from Terraform code
5. Apply Terraform code
6. Crash occurs instead of gracefully ignoring the fact that the registry has already been removed.

**Expected behavior**
If a read of a resource returns no result it should immediatly remove the resource from state file (if there is an easy to use unique identifier we should be using this to lookup values), assuming that we can differentiate between Harbor server being down and the actual resource not existing. This will allow a plan to either skip the deletion of the resource as it is already gone or it will plan the creation of the resource.

Current read resource code
```
func resourceGroupRead(d *schema.ResourceData, m interface{}) error {
	apiClient := m.(*client.Client)
	resp, _, _, err := apiClient.SendRequest("GET", d.Id(), nil, 200)
	if err != nil {
		return err
	}
```
What it should probably look like
```
func resourceGroupRead(d *schema.ResourceData, m interface{}) error {
	apiClient := m.(*client.Client)
	resp, _, _, err := apiClient.SendRequest("GET", d.Id(), nil, 200)
        if utils.ResponseWasNotFound(resp.Response) {
	        d.SetId("")
		return nil
	}
	if err != nil {
		return err
	}
```
**Additional context**
Having to run `terraform rm state <path of resource>` when ever a manual change occurs on a resource is not desired.

**Comment by taliesins** [comment]
#235 is a symptom of the problem but only for the project resource type

**Comment by naitmare01** [comment]
I have written a PR to fix the project and members resources. https://github.com/goharbor/terraform-provider-harbor/pull/356

That PR could be a foundation to update the rest of the resources as well.
