### ISSUE TITLE
Interest in ownership

### ISSUE THREAD

**Issue by alexba13** [goharbor/terraform-provider-harbor#238]
Hi @OrlinVasilev and @maintainer-team,
Like you have mentioned in the README file you are looking for someone who is taking the ownership of this tool.
I am interested in this topic.

Are you still looking for someone? If yes, it would be great to have an exchange about this.

Thanks!

Kind regards,
Alex

**Comment by OrlinVasilev** [comment]
Hi @alexba13 10000% looking for maintainers!!

**Comment by alexba13** [comment]
Ok, thanks @OrlinVasilev! :)

**Comment by OrlinVasilev** [comment]
@alexba13 - can you contact me in slack please so we can figure the maintainers info :)
