### ISSUE TITLE
harbor_retention_policy and schedule field needs Caps on value

### ISSUE THREAD

**Issue by MallocArray** [goharbor/terraform-provider-harbor#239]
**Describe the bug**
retention_policy documentation shows schedule values in all lower case, but using this with Harbor 2.5.3 results in repeated changes by the provider flipping from "Daily" to "daily"
https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs/resources/retention_policy#schedule

Setting the .tf file to have the first letter capitalized results in "No changes." result as expected

**To Reproduce**
```yaml
resource "harbor_retention_policy" "test" {
  scope    = harbor_project.test.id
  schedule = "daily"
  rule {
    most_recently_pushed = 5
    repo_matching        = "**"
    tag_matching         = "**"
  }
}
```

**Expected behavior**
Repeated runs would show no changes, when in actuality terraform wants to change the schedule value from upper case to lower case.

**Screenshots**
```
  ~ resource "harbor_retention_policy" "ansible" {
        id       = "/retentions/1"
      ~ schedule = "Daily" -> "daily"
        # (1 unchanged attribute hidden)

        # (2 unchanged blocks hidden)
    }
```

**Desktop (please complete the following information):**
 - OS: RHEL 8
 - Terraform 1.1.2
 - Provider version 3.5.0
 - Harbor 2.5.3

**Additional context**

**Comment by flbla** [comment]
Thank you, I fixed the doc
