### ISSUE TITLE
harbor_project_member_group are always replaced

### ISSUE THREAD

**Issue by Michenux** [goharbor/terraform-provider-harbor#244]
harbor_project_member_group are always recreated.

Example of plan output :
```
# harbor_project_member_group.registries["quay-io"] must be replaced
-/+ resource "harbor_project_member_group" "registries" {
      ~ id         = "/projects/6/members/23" -> (known after apply)
      + member_id  = (known after apply)
      ~ project_id = "/projects/6" -> "6" # forces replacement
        # (3 unchanged attributes hidden)
    }
```

I have the opposite behaviour as in [Issues 175](https://github.com/goharbor/terraform-provider-harbor/issues/175)

My stack:
- terraform harbor provider : 3.7.1
- terraform: 1.1.9
- OS: osx

**Comment by flbla** [comment]
@michenux: I cannot reproduce your issue. Could you please share your terraform code ?
