### ISSUE TITLE
harbor_interrogation_services can't detect drift in the configuration

### ISSUE THREAD

**Issue by naitmare01** [goharbor/terraform-provider-harbor#245]
**Describe the bug**
Set the resource harbor_interrogation_services, https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs/resources/interrogation_services, and applied. The state was updated but nothing happened on our Harbor installation.

**To Reproduce**
1. resource "harbor_interrogation_services" "vuln_scanning" {
  vulnerability_scan_policy = "Daily"
}
2. `terraform apply`
3. `yes`
4. Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
5. Change appeared as expected in GUI.
6. Change value manually in GUI.
7. `terraform apply` or `terraform plan`
8. `No changes. Your infrastructure matches the configuration.`

> Note that if the resource is updated and we are running `terraform apply` or `terraform plan` the changes will show and be updated. The main issue seems to be that Terraform can't detect drift in the configuration. It only looks for changes in the state and not the remote resource.

**Expected behavior**
Harbor GUI interrogation service schedule should be changed to match our terraform config. 

**Screenshots**
N/A

EDIT: Updated how to reproduce and added a note.

**Comment by naitmare01** [comment]
Update, seeing the exact same issue when using https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs/resources/tasks that is being deprecated in the next major version.

**Comment by flbla** [comment]
@naitmare01 : I cannot reproduce with latest provider version, both resources are working on my side
could you please tell me your provider version and Harbor version?

**Comment by naitmare01** [comment]
Harbor: v2.5.0-98e1b82
Terraform provider: 3.7.1

**Comment by flbla** [comment]
I'm not able to reproduce with Harbor 2.5.0 and provider 3.7.1

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # harbor_interrogation_services.vuln_scanning will be created
  + resource "harbor_interrogation_services" "vuln_scanning" {
      + id                        = (known after apply)
      + vulnerability_scan_policy = "Daily"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

harbor_interrogation_services.vuln_scanning: Creating...
harbor_interrogation_services.vuln_scanning: Creation complete after 0s [id=/system/scanAll/schedule]
```


![image](https://user-images.githubusercontent.com/11298399/192793157-e8aae358-d121-4475-a7d8-e43fe5bd693b.png)

Can you launch terraform with debug and copy logs ?

**Comment by naitmare01** [comment]
Alright, I've investigated further and it seems that I can set the schedule when there is no resource in the state.
I.e. first run. 
Then it is set.

If we do change the value in the GUI and runs `terraform plan` we get `No changes. Your infrastructure matches the configuration.`
If we do however change our config from e.g. `Daily` --> `Weekly` we get the following:

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # harbor_interrogation_services.vuln_scanning will be updated in-place
  ~ resource "harbor_interrogation_services" "vuln_scanning" {
        id                        = "/system/scanAll/schedule"
      ~ vulnerability_scan_policy = "Daily" -> "Weekly"
    }

Plan: 0 to add, 1 to change, 0 to destroy
```

The problem seems to lie in that Terraform can't detect any drift in the configuration.

**Comment by naitmare01** [comment]
I have written a [pull request](https://github.com/goharbor/terraform-provider-harbor/pull/271) which should fix this issue. Take a look an provide feedback.
