### ISSUE TITLE
support for bandwidth in harbor_replication 

### ISSUE THREAD

**Issue by 1337andre** [goharbor/terraform-provider-harbor#250]
Please support bandwidth in  harbor_replication

additional field should be:
speed: X (in kbit)

**Comment by naitmare01** [comment]
@1337andre I have created a PR which implements this.

**Comment by flbla** [comment]
this is now included with [3.8.2](https://github.com/goharbor/terraform-provider-harbor/releases/tag/v3.8.2)
thank you @naitmare01
