### ISSUE TITLE
Add new maintainer to Terraform registry

### ISSUE THREAD

**Issue by matttrach** [goharbor/terraform-provider-harbor#263]
**Is your feature request related to a problem? Please describe.**
It is hard sometimes to find quality providers, knowing that your Terraform provider is supported by the official community is helpful to me personally and an org that I represent.

**Describe the solution you'd like**
Please deploy this provider to Terraform Registry.io as goharbor/terraform-provider-harbor rather than BESTSELLER/terraform-provider-harbor.

**Describe alternatives you've considered**
I am currently using the BESTSELLER version of the provider, but it would be nice to have an official version.

**Comment by coutantal** [comment]
I totally agree with this suggestion !

**Comment by flbla** [comment]
Hi,
I'm happy to announce that the terraform Harbor provider is now available on the terraform registry : https://registry.terraform.io/providers/goharbor/harbor 😃
