### ISSUE TITLE
Configure Provider from Environment Variables

### ISSUE THREAD

**Issue by matttrach** [goharbor/terraform-provider-harbor#264]
**Is your feature request related to a problem? Please describe.**
I would like to be able to configure the username and password from environment variables, the way the HARBOR_URL is configurable. Ideally, I would not mention providers outside of the "versions.tf" which sets the version. This is possible if all of the options to configure a provider can be provided by env variables. This also allows me to manage permissions in my CI system, using a security tool like Vault or SOPS to inject username and password to environment variables at run time.

**Describe the solution you'd like**
Enable authorization via env variables, something like HARBOR_USERNAME, HARBOR_PASSWORD. 

**Describe alternatives you've considered**
OIDC login seems like a heavy alternative, otherwise I need to have an override.tf in Terraform to manage the secrets on my CI runner.

**Comment by 1337andre** [comment]
this vars are already honored now and we use them as port of our CI/CD 

```
HARBOR_URL
HARBOR_USERNAME
HARBOR_PASSWORD
HARBOR_IGNORE_CERT
```

have a look:
https://github.com/goharbor/terraform-provider-harbor/blob/a112dbf114d8a94fbedf1b0a13482f90ebd33de5/provider/provider.go#L27
