### ISSUE TITLE
Support harbor replication Flattening option

### ISSUE THREAD

**Issue by HSoulat** [goharbor/terraform-provider-harbor#265]
**Is your feature request related to a problem? Please describe.**
Harbor is providing a destination name flattening option. Terraform resource do not provide this option, so al replication uses the default option "Flattening all levels". 

**Describe the solution you'd like**
A target configuration could be : 

```
resource "harbor_replication" "replication" {
  name        = "name"
  action      = "pull"
  registry_id = "source_registry_id"
  dest_namespace = "dest_namespace"
 
  Flattening_level = ["None", "1", "2", "3", "All"]
}

```

**Comment by flbla** [comment]
Hi,
it's handled by this parameter : `dest_namespace_replace` : https://github.com/goharbor/terraform-provider-harbor/blob/master/docs/resources/replication.md#argument-reference

but the version with this param is not yet built
