### ISSUE TITLE
Terraform does not detect manual changes to a system robot account

### ISSUE THREAD

**Issue by LennartTimmers** [goharbor/terraform-provider-harbor#288]
Hi there,

**Context:**
We use harbor with multiple projects, 1 for each team. For these teams/projects we automatically create a system robot account. This system robot account has access to a few generic projects and the team project. We create all this configuration through Terraform by looping over a set of variables. 

**The bug**
Recently I made a manual change to one of the robot accounts for testing purposes. I figured I'd roll this manual change back using terraform, however when I executed a `Terraform plan` the provider did not detect any changes to the system robot accounts permissions even though I manually changed these. 

**To Reproduce**
1. Create a system robot account with a limited set of permissions through terraform 
2. Navigate to harbor > system robot accounts and change the permissions of the robot account you created through terraform. In my case I gave the robot account additional permissions on a project it did not yet have any on.
3. Navigate back to your terraform code and execute a `Terraform plan` command.
4. Terraform does not detect any changes to the robot account which you created.

**Expected behavior**
I'd expect Terraform to detect that the system robot account has additional permissions and that the plan will indicate that these will be removed when executing an apply. 

**Screenshots**
If the descriptions aren't clear I can provide some screenshots later but I'd have to setup a separate environment and recreate the issue there, as I can't share our production values.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Chrome
 - Harbor version: V2.6.2
 - Provider version: ~> 3.6.1

**Comment by naitmare01** [comment]
You are correct, it only find changes in `robot_id` and `full_name` right now.

Pseducode would be something like below but in a smarter way setting permissions on the blow funciton.
Just naively tested the below and that didn't work. We need to be smarter in finding how to detect drift in the permissions.

```go
func resourceRobotAccountRead(d *schema.ResourceData, m interface{}) error {
[...]
	d.Set("permissions", robot.Permissions)
}
```

https://github.com/goharbor/terraform-provider-harbor/blob/f6e57263164cf86e3b2f6c0fedc4dfb8e479e442/provider/resource_robot_account.go#L160
