### ISSUE TITLE
Incorrect import command example in registry.md/replication.md

### ISSUE THREAD

**Issue by pf0** [goharbor/terraform-provider-harbor#290]
**Describe the bug**
The current documentation as of v.3.8.1 contains a copy-paste error within two import command examples.

**Expected behavior**
The example within [registry.md ](https://github.com/goharbor/terraform-provider-harbor/blob/v3.8.1/docs/resources/registry.md#import)should actually look like this
` terraform import harbor_registry.main /registries/7 `..

Additonally, the example provided within [replication.md](https://github.com/goharbor/terraform-provider-harbor/blob/v3.8.1/docs/resources/replication.md#import) should also be corrected to 
` terraform import harbor_replication.main /replication/policies/1 `.

**Comment by flbla** [comment]
hi,
I don't understand the issue with this import command `terraform import harbor_registry.main /registries/7`
I see it, for the 2nd one

**Comment by pf0** [comment]
You are correct, it was my bad v.3.8.1 contains a correct import command for registries. However, on the main [documentation](https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs/resources/registry)  still links to v.3.7.1 and there it states an incorrect command.

**Comment by flbla** [comment]
the link you copy is the BESTSELLER/harbor provider which has been migrated to goharbor/harbor (this project) : https://registry.terraform.io/providers/goharbor/harbor/latest
