### ISSUE TITLE
Registry access_id and access_secret are not updated

### ISSUE THREAD

**Issue by stefan-sesser** [goharbor/terraform-provider-harbor#293]
**Describe the bug**
I have a `harbor_registry` with an existing access_id and access_secret in place. At some time I moved the credentials to a Vault instance and rotated them. Now I am trying to read the credentials via the Vault Terraform provider und update it in the registry.  
The code looks like this:
```
data "vault_generic_secret" "harbor" {
  path = "<path>"
}

resource "harbor_registry" "aws_ecr_test" {
  provider_name = "aws"
  name = "aws-ecr-test"
  endpoint_url = "<url_to_ecr>"
  access_id = data.vault_generic_secret.harbor.data["AWS_ACCESS_KEY_ID"]
  access_secret = data.vault_generic_secret.harbor.data["AWS_SECRET_ACCESS_KEY"]
  insecure = "false"
  description = "Test 123"
```
If I now run a `terraform apply` I get the following output:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # harbor_registry.aws_ecr_test will be updated in-place
  ~ resource "harbor_registry" "aws_ecr_test" {
      ~ access_id     = (sensitive value)
      ~ description   = "Test" -> "Test 123"
        id            = "/registries/7"
        name          = "aws-ecr-test"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

...

harbor_registry.aws_ecr_test: Modifying... [id=/registries/7]
2023-02-10T10:08:51.694Z [INFO]  Starting apply for harbor_registry.aws_ecr_test
2023-02-10T10:08:52.561Z [WARN]  Provider "provider[\"registry.terraform.io/goharbor/harbor\"]" produced an unexpected new value for harbor_registry.aws_ecr_test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .access_id: inconsistent values for sensitive attribute
harbor_registry.aws_ecr_test: Modifications complete after 1s [id=/registries/7]

```
If I now have a look on Harbor itself, I can see, that the description is updated, but the access_id not.
Another `tarraform plan` will again show that it will update the access_id only.

**To Reproduce**
1. Import an esxisting harbor_registry with `terraform import`
2. Create new credentials and move them to Vault 
3. Read the credentials via the Vault plugin
4. Run `terraform apply`

**Expected behavior**
access_id and access_secret are updated in Harbor

**Desktop (please complete the following information):**
 - provider: plugin process exited: path=.terraform/providers/registry.terraform.io/goharbor/harbor/3.8.2/linux_amd64/terraform-provider-harbor_v3.8.2

**Comment by flbla** [comment]
should be fixed with v3.8.3
