### ISSUE TITLE
Harbor_robot_account import documentation not available

### ISSUE THREAD

**Issue by deepbrook** [goharbor/terraform-provider-harbor#309]
**Describe the bug**
Instructions on how to import a `harbor_robot_account` resource block's state is not rendered on the terraform registry.

**To Reproduce**
[Open up the docs and see it's missing the `import` section.](https://registry.terraform.io/providers/goharbor/harbor/latest/docs/resources/robot_account#import)
It appears to simply not exist in the related `md` as well: https://github.com/goharbor/terraform-provider-harbor/blob/main/docs/resources/robot_account.md

**Comment by Tim-herbie** [comment]
It Import seems to work partly. I can import robots with the following syntax:
`terraform import harbor_robot_account.robot /robots/123`

123 is the robot_id, which can be found here under `/api/v2.0/robots`


Here the Terraform Code:
```hcl
resource "harbor_robot_account" "robot" {
  name        = "example-project"
  description = "project level robot account"
  level       = "project"
  permissions {
    access {
      action   = "pull"
      resource = "repository"
    }
    access {
      action   = "push"
      resource = "repository"
    }
    kind      = "project"
    namespace = harbor_project.main.name
  }
}
```

But I had to add the `level` and `system` parameters in the .tfstate file manually if I don´t want that terraform recreate this.

But it´s missing in the documentation, that is right.

**Comment by naitmare01** [comment]
I have created a PR to update the docs. https://github.com/goharbor/terraform-provider-harbor/pull/358

Regarding the manual setting of `level`, `system` and `permissions` I'm fairly certain that is related to #288 and how the read-function for robot-accounts are implemented.
