### ISSUE TITLE
Add support for Log Rotation configuration

### ISSUE THREAD

**Issue by vtrtmnn** [goharbor/terraform-provider-harbor#315]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to configure the Log Rotation through this terraform provider (UI: "Administration" -> "Clean Up" -> "Log Rotation", REST-Endpoint: "/system/purgeaudit/schedule").

**Describe the solution you'd like**
I'd like to be able to configure the Log Rotation through this provider. Values you would want to set are analogous to the ones from the related API-Request.
`{"parameters":{"audit_retention_hour":integer,"dry_run":boolean, "include_operations":"create,delete,pull"},"schedule":{"type":"Hourly","cron":"0 0 * * * *"}}`

**Additional context**
![Screenshot_20230414_143357](https://user-images.githubusercontent.com/114233584/232044696-618178bb-3211-401e-989b-e459dcaf6b59.png)

**Comment by flbla** [comment]
hi,
thanks for the feature request, it's available with [v3.9.3](https://github.com/goharbor/terraform-provider-harbor/releases/tag/v3.9.3)
