### ISSUE TITLE
Primary auth mode

### ISSUE THREAD

**Issue by guyguy333** [goharbor/terraform-provider-harbor#319]
**Is your feature request related to a problem? Please describe.**

In the Harbor UI, we can configure OIDC as a primary auth. It's currently missing in this terraform provider.

<img width="577" alt="Screenshot 2023-05-04 at 22 57 44" src="https://user-images.githubusercontent.com/4040959/236315766-b8e69860-f939-4ed3-834d-c9e8237f8c3b.png">

**Describe the solution you'd like**

Enable this option to be configurable through this terraform provider, surely in harbor_configuration resource.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by flbla** [comment]
Hi @guyguy333,
thanks for the issue, it will be available in the next release
