### ISSUE TITLE
Feature: Enrich harbor_project data source

### ISSUE THREAD

**Issue by slushysnowman** [goharbor/terraform-provider-harbor#323]
**Is your feature request related to a problem? Please describe.**
It would be really useful to be able to determine if a project is a proxy cache project in Terraform (especially in combination with this [feature request](https://github.com/goharbor/terraform-provider-harbor/issues/322))

This would allow a lot more permissions to be set dynamically, and make the provider much more flexible.

**Describe the solution you'd like**
Add a new attribute to `harbor_project` data source, which will indicate if it is a proxy cache project or not. Something like `type: proxy_cache`

**Comment by flbla** [comment]
Hi @slushysnowman,
Thank you for the feature request, it will be available with release v3.10.0.

**Comment by slushysnowman** [comment]
same for this, really appreciated @flbla !
