### ISSUE TITLE
ldap group creation fail

### ISSUE THREAD

**Issue by HSoulat** [goharbor/terraform-provider-harbor#325]
**Describe the bug**
LDAP group creation failed as ldap_group_dn parameter is required by Harbor API but not implemented in resource definition.

**To Reproduce**
```
resource "harbor_group" "test" {
  group_name = "Harbor_Group"
  group_type = 1
}
```

**Expected behavior**
```
resource "harbor_group" "test" {
  group_name = "Harbor_Group"
  group_type = 1
  ldap_group_dn = "cn=harbor_group,ou=groups,dc=domain,dc=local"
}
```

**Additional context**

- Provider Version: 3.8.4
- Harbor Version: 2.7.1

**Comment by flbla** [comment]
Hi,
thanks for the issue.
It will be available in the next provider release
