### ISSUE TITLE
harbor_project proxy_cache

### ISSUE THREAD

**Issue by HSoulat** [goharbor/terraform-provider-harbor#333]
Allow creation of proxy_cache project. For now this option is not available through terraform provider. 

Sample : 
```
resource "harbor_project" "project" {
  name                   = var.project_name
  public                 = false
  vulnerability_scanning = true
  proxy_cache_endpoint = "https://192.168.1.1"
}
```

**Comment by flbla** [comment]
Hello @HSoulat,
did you try : https://github.com/goharbor/terraform-provider-harbor/blob/main/docs/resources/project.md#harbor-project-example-as-proxy-cache ?
