### ISSUE TITLE
[Bug] - Failure to create webhook 

### ISSUE THREAD

**Issue by a-chartier** [goharbor/terraform-provider-harbor#340]
**Describe the bug**
When attempting to create a project/repository web-hook I am getting 404 errors. I believe it's because of the url building in [this](https://github.com/goharbor/terraform-provider-harbor/blob/main/provider/resource_harbor_project_webhook.go#L70-L83) code block.

The generated URL appears to be https://something.com/api/v2.031/webhook/policies. (no `/` before the project id). The [SenRequest](https://github.com/goharbor/terraform-provider-harbor/blob/main/client/client.go#L37) function seems to be a direct concatenation of URL + PATH

**To Reproduce**
I believe if you attempt to create a webhook it will fail in the current configuration.

**Expected behavior**
It should create a web-hook

**Additional context**
- Provider Version v3.9.3

*Note*: I purposefully left out the protocol so it would print the URL during the error 

<img width="667" alt="image" src="https://github.com/goharbor/terraform-provider-harbor/assets/113202129/f678974b-06bd-4656-b7a7-0284433488be">

**Comment by flbla** [comment]
Hello @a-chartier,
in the example : https://github.com/goharbor/terraform-provider-harbor/blob/main/docs/resources/project_webhook.md#resource-harbor_project_webhook

`project_id  = harbor_project.main.id`

harbor_project.main.id is /projects/**ID**

can you try with it ?

**Comment by a-chartier** [comment]
I see - So project ID is not just the id but the prefixed `/projects/id`.  I don't think I had seen that noted anywhere, I was just using the project since..well that's what it is lol 


That worked though so I guess this can be close or perhaps it should be documented since it's not just a `project_id` that is expected.
