### ISSUE TITLE
Project member group import: the resource's type argument is a null value

### ISSUE THREAD

**Issue by barberae** [goharbor/terraform-provider-harbor#345]
**Describe the bug**
We are trying to import the project's member group from an Harbor instance. We created the import block as described here (https://www.youtube.com/watch?v=y8_5Ud29W8o&pp=ygUQdGVycmFmb3JtIGltcG9ydA%3D%3D) but when we launch the command "_terraform plan -generate-config-out=<file_name>_" we receive an error in the output:

<img width="227" alt="image" src="https://github.com/goharbor/terraform-provider-harbor/assets/13900871/692e90af-3f56-485c-bbea-c67efed0261c">

It seems the resource created doesn't return a correct value for the required argument type. This will force us to manually insert it. 

**To Reproduce**
Create an import block and execute the command "_terraform plan -generate-out-config=<file_name_> as describe in the video above and check the <file_name> content: the argument type should be empty.

**Expected behavior**
We expect to see a value like: "ldap", "internal" or "oidc".

**Additional context**
Provider Version: 3.9.3
Terraform Version: 1.5
Harbor Version: v2.8.0-89ef156d

**Comment by flbla** [comment]
Could you please copy your code, I don't have such issue.
Did you set the "type" field ? it's a mandatory field.
