### ISSUE TITLE
Ability to authentificate to harbor using Bearer Token

### ISSUE THREAD

**Issue by ilyesAj** [goharbor/terraform-provider-harbor#383]
**Is your feature request related to a problem? Please describe.**

When harbor is configured with OIDC authentification, all the requests needs to be authenticated using `bearer token`. 
Related: 
- https://github.com/goharbor/harbor/issues/10597#issuecomment-596642414
- https://github.com/goharbor/harbor/issues/13683
- https://github.com/goharbor/harbor/issues/16647#issuecomment-1094819541

**Describe the solution you'd like**

Add the ability to inject bearer token within the provider configuration

**Describe alternatives you've considered**

- create a robot account with username/password and use it with the provider. didn't work due to lack of permissions: https://github.com/goharbor/harbor/issues/14145

**Comment by mubn** [comment]
Any chance, to be able soon, to authenticate within the provider at a Harbor instance via a bearer token?
