### ISSUE TITLE
Robot account with permissions to pull across all and push project specific

### ISSUE THREAD

**Issue by theabrar** [goharbor/terraform-provider-harbor#426]
https://github.com/goharbor/harbor/issues/20186

**Describe the bug**
I’m trying to create a system level robot account with permissions to
- pull repository across all projects
- push repository to project “my-project-name”

as mentioned in the harbor terraform provider documentation [here](https://registry.terraform.io/providers/goharbor/harbor/latest/docs/resources/robot_account), however, having the namespace = "*" seems to override other permissions and does not allow the push to the project.

**To Reproduce**
using the code below:

```
variable "harbor_projects" {
  type = list(string)
  default = [
    "1",
    "2",
    "3",
    "4"
  ]
}
```

```
resource "harbor_robot_account" "robot_accounts" {
  for_each    = toset(var.harbor_projects)
  name        = "${each.key}-ci"
  description = "System level Robot account for Project ${each.key}"
  level       = "system"
  permissions {
    access {
      action   = "pull"
      resource = "repository"
    }
    access {
      action   = "push"
      resource = "repository"
    }
    kind      = "project"
    namespace = harbor_project.projects[each.key].name
  }
  permissions {
    access {
      action   = "pull"
      resource = "repository"
    }
    kind      = "project"
    namespace = "*"
  }
}
```

**Expected behavior**
As mentioned in the documentation, expecting the robot account should have access to pull from all projects and push only to specified project/repository.

**Additional context**

- Provider Version [3.10.8]
- Terraform Version [1.7.2]
- Harbor Version [2.10.1-b7b88476]

**Comment by flbla** [comment]
Hi @theabrar 
it looks like it's not possible to do it with the Harbor API neither the UI , so neither with the terraform provider
can you confirm : @wy65701436 we can't have a "Cover all projects" with pull option AND specific for a project with pull/push

you can try with the UI, if you select "Cover all projects", you can't anymore select specific projects:
![image](https://github.com/goharbor/terraform-provider-harbor/assets/11298399/d7431b89-1ecd-4229-a87c-0b64a87959e7)

**Comment by flbla** [comment]
after some more tests, i think it's just the UI which doesn't show it as I can see it with an API call :
![image](https://github.com/goharbor/terraform-provider-harbor/assets/11298399/e1e61ca4-68ab-4c0a-bcff-f3828f2f6f69)

I tried to push to the project library (the project on which I allowed the push) and it worked


```
(⎈ |kind-kind:default)➜  example git:(main) ✗ docker login localhost -u 'robot$ci'
Password:
WARNING! Your password will be stored unencrypted in /home/florian/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

(⎈ |kind-kind:default)➜  example git:(main) ✗ docker tag alpine:latest localhost/library/alpine:latest
(⎈ |kind-kind:default)➜  example git:(main) ✗ docker push localhost/library/alpine:latest
The push refers to repository [localhost/library/alpine]
d4fc045c9e3a: Pushed
latest: digest: sha256:6457d53fb065d6f250e1504b9bc42d5b6c65941d57532c072d929dd0628977d0 size: 528
```

**Comment by flbla** [comment]
I will close this and reopen the other ticket on Harbor project

**Comment by theabrar** [comment]
thanks @flbla for checking, were you able to pull from a different project other than the `library` using `robot$ci`

**Comment by flbla** [comment]
yes :

"test" is a Private project with alpine:latest in it :
![image](https://github.com/goharbor/terraform-provider-harbor/assets/11298399/bad98388-9c52-47aa-8595-66c8db32648e)


(⎈ |kind-kind:default)➜  example git:(main) ✗ docker login localhost -u 'robot$ci'
Password:
WARNING! Your password will be stored unencrypted in /home/florian/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

(⎈ |kind-kind:default)➜  example git:(main) ✗ docker pull localhost/test/alpine:latest
latest: Pulling from test/alpine
4abcf2066143: Already exists
Digest: sha256:6457d53fb065d6f250e1504b9bc42d5b6c65941d57532c072d929dd0628977d0
Status: Downloaded newer image for localhost/test/alpine:latest
localhost/test/alpine:latest

and in the project logs, it's the "robot$ci" which pull it :
![image](https://github.com/goharbor/terraform-provider-harbor/assets/11298399/a669756f-f120-4559-9b86-dc7983b9d582)
