### ISSUE TITLE
harbor_project_member_group group gets not deleted

### ISSUE THREAD

**Issue by steled** [goharbor/terraform-provider-harbor#437]
**Describe the bug**
When I'm destroying a `harbor_project_member_group` resource the depending group is not being removed in Harbor.

**To Reproduce**
- create a `harbor_project_member_group` with the code below:

```yaml
resource "harbor_project_member_group" "group" {
  project_id    = harbor_project.project.id
  group_name    = "test_project_admin"
  role          = "projectadmin"
  type          = "oidc"
}
```

- run `terraform apply`
- check that the group is created in the UI
- run `terraform destroy`
- check that the group is still available in the UI

**Expected behavior**
I would expect that the group also gets removed when I run `terraform destroy`

**Additional context**

- Provider Version: v3.10.9
- Terraform Version: v1.8.0
- Harbor Version: v2.10.1-b7b88476

**Comment by flbla** [comment]
harbor_project_member_group handle the membership not the group itself
it should be probably handle by harbor itself in the garbage collect feature
