### ISSUE TITLE
harbor_project not detecting changes to some deployment security settings

### ISSUE THREAD

**Issue by BlueIce** [goharbor/terraform-provider-harbor#453]
**Describe the bug**

I have a Harbor project which is created via terraform:
```terraform
resource "harbor_project" "main" {
  name                   = "xxx"
  public                 = false
  vulnerability_scanning = true
  enable_content_trust   = false
  deployment_security    = "high"
  storage_quota          = 20
  force_destroy          = true
}
```
When the checkbox `Prevent vulnerable images from running` or the corresponding severity drop-down is changed via UI, the provider does not notice the changes when doing a terraform plan.

**To Reproduce**

1. Create a project (see above)
2. In the Harbor UI go to project configuration. Under "Deployment security" section: Change the severity to `Medium`, uncheck `Prevent vulnerable images from running` and the save
3. Do a terraform plan => Terraform reports no changes detected

**Expected behavior**

In step 3 from above: Terraform reports changes for the two attributes

**Additional context**

If you now go on and also change another property (for example uncheck `Automatically scan images on push`) and again do a terraform plan, only this change will be detected:
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # module.XXXXX_harbor_project.harbor_project.main will be updated in-place
  ~ resource "harbor_project" "main" {
        id                          = "/projects/XXX"
        name                        = "XXXXX"
      ~ vulnerability_scanning      = false -> true
        # (9 unchanged attributes hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```
But if you do now a terraform apply, all three properties will be restored.

- Provider Version 3.10.12
- Terraform Version 1.5.7
- Harbor Version 2.11.0

**Comment by BlueIce** [comment]
I did some digging through the code.
It seems the two attributes are not propagated, when the project is read: https://github.com/goharbor/terraform-provider-harbor/blob/v3.10.12/provider/resource_project.go#L106-L158

**Comment by flbla** [comment]
hi @BlueIce ,
Thank you for the bug report
This will be fixed in the next version

**Comment by BlueIce** [comment]
Thanks for looking into this so fast. :smiley:
