### ISSUE TITLE
`registry_id` differs between `harbor_registry` and `harbor_project`

### ISSUE THREAD

**Issue by q-b** [goharbor/terraform-provider-harbor#460]
The `registry_id` output from `harbor_registry` is `/registries/<id>`.
The input expected by `harbor_project` for the field is `<id>`

[The proxy example in the documentation is not valid](https://registry.terraform.io/providers/goharbor/harbor/3.10.14/docs/resources/project#proxy)

```
harbor_project.projects["example"]: Refreshing state... [id=/projects/22]
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 18, in resource "harbor_project" "projects":
│   18:   registry_id                 = each.value.registry_id
│     ├────────────────
│     │ each.value.registry_id is "/registries/5"
│ 
│ Inappropriate value for attribute "registry_id": a number is required.
╵
```

- Provider Version 3.10.12
- Terraform Version 1.9.2
- Harbor Version 2.10.0

**Comment by flbla** [comment]
hi @q-b ,
could you please provide more code ?

I tried with following code and registry_id is an int (furthermore, I would crash terraform if it was a string, as the type of registry_id is int : https://github.com/goharbor/terraform-provider-harbor/blob/main/provider/resource_registry.go#L54 and not string)

```
resource "harbor_registry" "dockerhub" {
  provider_name = "docker-hub"
  name          = "test_docker_harbor"
  endpoint_url  = "https://hub.docker.com"

}

output "registry_id" {
  value = harbor_registry.dockerhub.registry_id
}
```

terraform apply :

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
registry_id = 1
```

**Comment by q-b** [comment]
You are right, it was a mistake in the output where `.id` was used instead of `.registry_id`, sorry.
