### ISSUE TITLE
Cannot create a robot account with namespace value "*"

### ISSUE THREAD

**Issue by sani-vv** [goharbor/terraform-provider-harbor#465]
**Describe the bug**
I am trying to create a `robot` account with access to `all` projects. Therefore I used `*` as a value for `namespace` parameter of `permission` block under `harbor_robot_account` resource.

The terraform plan executes properly but during terraform apply I get the following error -

> 
> │ Error: [ERROR] unexpected status code got: 404 expected: 201 
> │  {"errors":[{"code":"NOT_FOUND","message":"project * not found"}]}
> │ 
> │ 
> │   with harbor_robot_account.project,
> │   on main.tf line 41, in resource "harbor_robot_account" "project":
> │   41: resource "harbor_robot_account" "project" {
> │ 
> 

**To Reproduce**
1. Create a `harbor_robot_account` resource

```
resource "harbor_robot_account" "project" {
  name        = "example-project"
  description = "project level robot account"
  level       = "project"
  permissions {
    access {
      action   = "push"
      resource = "repository"
    }
    kind      = "project"
    namespace = "*"
  }
}
```

2. Perform terraform apply and accept the changes

> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   + create
> 
> Terraform will perform the following actions:
> 
>   # harbor_robot_account.project will be created
>   + resource "harbor_robot_account" "project" {
>       + description = "project level robot account"
>       + disable     = false
>       + duration    = -1
>       + full_name   = (known after apply)
>       + id          = (known after apply)
>       + level       = "project"
>       + name        = "example-project"
>       + robot_id    = (known after apply)
>       + secret      = (sensitive value)
> 
>       + permissions {
>           + kind      = "project"
>           + namespace = "*"
> 
>           + access {
>               + action   = "push"
>               + effect   = "allow"
>               + resource = "repository"
>             }
>         }
>     }
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes

**Expected behavior**
A robot account with access to `all` projects with `push` permission should be created.

- Provider Version [3.10.15]
- Terraform Version [1.5.5]
- Harbor Version [2.10.3-c8c11b46]

**Comment by flbla** [comment]
Hi,
It should be a system robot account and not a projet robot account (system are global, projet are local to a specific project : https://registry.terraform.io/providers/goharbor/harbor/latest/docs/resources/robot_account)

```
resource "harbor_robot_account" "project" {
  name        = "example-project"
  description = "project level robot account"
  level       = "system"
  permissions {
    access {
      action   = "push"
      resource = "repository"
    }
    kind      = "project"
    namespace = "*"
  }
}
```

![image](https://github.com/user-attachments/assets/c472dcdf-1ad2-4ece-908b-0ca3ca1dda85)
