### ISSUE TITLE
The disabled attribute for harbor_immutable_tag_rule defaults to false on creation

### ISSUE THREAD

**Issue by nafaa-tayachi** [goharbor/terraform-provider-harbor#477]
**Describe the bug**

When creating a new `harbor_immutable_tag_rule` resource with `disabled=true`, terraform applies the resource with `disabled=false`. The subsequent `terraform apply` corrects the value and sets it to `true`.

**To Reproduce**

- create a new `harbor_immutable_tag_rule` with `disabled=true`, below is the plan:
```
  # harbor_immutable_tag_rule.immutable_tag_rule[0] will be created
  + resource "harbor_immutable_tag_rule" "immutable_tag_rule" {
      + disabled      = true
      + id            = (known after apply)
      + project_id    = "/projects/1"
      + repo_matching = "**"
      + tag_matching  = "**"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
- the immutable tag rule is shown as active in Harbor UI

- run `terraform apply` again with no change,  the output will show that the `disabled` attribute changes from `false` to `true`
```
  # harbor_immutable_tag_rule.immutable_tag_rule[0] will be updated in-place
  ~ resource "harbor_immutable_tag_rule" "immutable_tag_rule" {
      ~ disabled      = false -> true
        id            = "/projects/1/immutabletagrules/1"
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Expected behavior**
The immutable tag rule should be created with `disabled=true` on the first `terraform apply` command.

**Additional context**

- Provider Version: `v3.10.15`
- Terraform Version: `v1.6.4`
- Harbor Version: `v2.10.0-6abb4eab`

**Comment by flbla** [comment]
hi @nafaa-tayachi,
thank you for the bug report
Indeed, it seems the Harbor API doesn't allow to create an immutable tag rule with `disabled` parameter set to true.
i will try to do a workaround
