### ISSUE TITLE
Quay registry creation

### ISSUE THREAD

**Issue by scottcrossen** [goharbor/terraform-provider-harbor#86]
**Describe the bug**

Hey first of all: great project!

This bug/feature request is for quay.io support. Note that the enum exists at https://github.com/BESTSELLER/terraform-provider-harbor/blob/41d356fdea6521bf16c594a7246975567baed0ff/client/registry.go#L40 but it is still impossible to create quay registries in Terraform even though it's possible from the UI.

**To Reproduce**
Define a resource for a quay registry.

```
resource "harbor_registry" "quay" {
  provider_name = "quay"
  name          = "quay"
  endpoint_url  = "https://quay.io"
}
```

This will cause:

```
Error: [ERROR] unexpected status code got: 400 expected: 201 
 {"errors":[{"code":"BAD_REQUEST","message":"the registry is unhealthy"}]}
 ```
 
Note that even if access is setup reasonably (`access_id: "json_file"` and a valid cli_password/username as per [here](https://goharbor.io/docs/2.1.0/administration/configuring-replication/create-replication-endpoints/) it will still fail. It will also fail if `access_id: ""`.

**Expected behavior**
A valid registry

**Additional context**
Harbor auto-fills the "access_id" in the web UI as "json_file" and throws the same error until the auto-filled value is removed or a valid "access_secret" is passed. In Terraform, I attempted to overwrite this default value with an empty string but that does not work unfortunately.

**Comment by sidewinder12s** [comment]
With latest, this appears to work:

```hcl
resource "harbor_registry" "quay" {
  provider_name = "quay-io"
  name          = "Quay"
  endpoint_url  = "https://quay.io"
}
```

Might just need to update the alias'

**Comment by Tim-herbie** [comment]
This still needs to be adjusted in the official documentation

provider_name: quay -> quay-io
